### ISSUE TITLE
Koa metrics

### ISSUE THREAD

**Issue by jonathanzO** [XanderD99/strapi-prometheus#11]
**Is your feature request related to a problem? Please describe.**
Can Koa metrics please be included into the strapi-prometheus plugin

**Describe the solution you'd like**

Include Koa in the metrics similar to https://github.com/PayU/prometheus-api-metrics

e.g. 
Plain text:
```
...  

#HELP koajs_number_of_open_connections Number of open connections to the Koa.js server. 
#TYPE koajs_number_of_open_connections gauge  
koajs_number_of_open_connections 0
```

JSON:
```
...
{
    "help": "Number of open connections to the Koa.js server",
    "name": "koajs_number_of_open_connections",
    "type": "gauge",
    "values": [
        {
            "value": 0,
            "labels": {}
        }
    ],
    "aggregator": "sum"
}
```

**Additional context**
Current strapi-prometheus version: 1.2.0

Thanks

**Comment by XanderD99** [comment]
Great idea, I'll have a look at how this can be done within strapi. I don't know when just yet but I'll do it as fast as I can ;)

**Comment by XanderD99** [comment]
Merged and published version 1.3.0 which now includes a metric for open connections, with a config (interval) to define at what interval they should be retrieved together with other metrics.

**Comment by jonathanzO** [comment]
Thank you @XanderD99 for the update, 
I saw that there is logging of the count in the terminal 

https://github.com/XanderD99/strapi-prometheus/pull/12/commits/90bc074e2c32351054b9382c0c2fff3d85a44ff4#diff-0c83de896eaf3bfe38bbcb5ee8fabdff603a4dabdd686887e2afc3f58566ea8cR10

Is it possible to remove the console log

Thanks!

**Comment by XanderD99** [comment]
My bad, must have left it there when debugging.

I'll remove it, tomorrow morning!

**Comment by XanderD99** [comment]
log has been removed in 1.3.1

**Comment by jonathanzO** [comment]
Thanks!
