### ISSUE TITLE
Great Project! Will there be support for graphql?

### ISSUE THREAD

**Issue by pcriadoperez** [XanderD99/strapi-prometheus#13]
First congrats on this great project!
I wanted to ask do see also integrating with the apollo server side of strapi?

**Comment by XanderD99** [comment]
That's a great idea haven't used the graphql side of strapi so this hasn't come to my mind yet. 

But just so that I understand correctly, you would like graphql metrics or do you want the endpoints to be queryable with graphql?

**Comment by pcriadoperez** [comment]
Correct graphql metrics. I'm having issues knowing what queries are slow, but they all sue the same endpoint `/graphql`
As strapi uses apollo server I was wondering if something like this would be possible (https://www.apollographql.com/docs/technotes/TN0003-opentelemetry-traces-to-prometheus/#prometheus-setup)

**Comment by XanderD99** [comment]
Had a look today and found some plugins for apollo server but they did not show up in the metrics yet. But I'll update this thread if I manage to find a solution!

**Comment by sunnyunde-xooa** [comment]
@XanderD99 do get which graphql query was called. As there might be different type of graphql queries being called. I want to narrow down the metrics on different ones
