### ISSUE TITLE
Apollo metrics always returning le=+inf

### ISSUE THREAD

**Issue by pcriadoperez** [XanderD99/strapi-prometheus#14]
**Describe the bug**
Apollo metrics not falling into correct buckets, enve though requests are around 100ms and should fall into the defined bucket of 0.1
Metrics only shows one bucket of +inf

**To Reproduce**
1. Activate Graphql metrics
2. Do several graphql calls
3. check /metrics

**Expected behavior**
Requests will fall into respective buckets

**Comment by XanderD99** [comment]
buckets should now be filled correctly. Mind I changed the names of some metrics ending in 'seconds' to end in just 's'.
