### ISSUE TITLE
http metrics error in middleware 

### ISSUE THREAD

**Issue by ponomarevkonst** [XanderD99/strapi-prometheus#16]
**Describe the bug**
If `enabledMetrics.http` is set to `false` some metrics (`requestDuration`, `requestSize`, `responseSize`) are still trying to be collected in middleware and it throws an error.

**To Reproduce**
1. Create strapi app
2. Go to `app/config/plugins.js`
3. Set `enabledMetrics.http` to `false`
4. Start the app with console `npm run strapi console`
5. Check random endpoint in the browser (e.g. `http://localhost:1337/admin`)
6. You will get `TypeError: requestEnd is not a function` in `node_modules/strapi-prometheus/server/middlewares/index.js:26:9`

**Expected behavior**
It should not throw an error and not collect any metrics.

**Comment by XanderD99** [comment]
v1.6.0 has been released on npm with this bug fix :)
