### ISSUE TITLE
Not compatible anymore with the latest version of Strapi 4.15.4

### ISSUE THREAD

**Issue by lrasata** [XanderD99/strapi-prometheus#19]
**Describe the bug**
Not compatible anymore with the latest version of Strapi 4.15.4

**To Reproduce**
1. add in the dependecies in package.json in a strapi application
```
  "dependencies": {
     "@strapi/plugin-i18n": "4.15.4",
    "@strapi/plugin-users-permissions": "4.15.4",
    "@strapi/strapi": "4.15.4",
    "strapi-prometheus": "^1.8.0",
 ```
2. run yarn install

**Expected behavior**
yarn install should cmplete without any erros

**Current behaviour**
got the following error : 

`@strapi/plugin-i18n@4.15.4: The engine "node" is incompatible with this module. Expected version ">=18.0.0 <=20.x.x". Got "16.17.1"` 

then upgraded to node v20.9.0, then having another error : 
`strapi-prometheus@1.8.0: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=18.x.x". Got "20.9.0"`

when using node v18.8.2 (latest LTS), I have the following error :  
```
error .../strapi-cms/node_modules/sharp: Command failed.
Exit code: 127
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
```

**Desktop (please complete the following information):**
 - OS: MacOS 14.1.1  
 - Version : strapi-prometheus 1.8.0
 - strapi v4.15.4

**Comment by XanderD99** [comment]
Yeah there was still a part in the package.json that only allowed node 14 to 18, removed that as it isn't valid anymore. v1.8.1 should resolve your issue :)

**Comment by lrasata** [comment]
Thanks ! this works for me
