### ISSUE TITLE
http_request_duration_seconds is missing when using Strapi v4.16.2 

### ISSUE THREAD

**Issue by lrasata** [XanderD99/strapi-prometheus#20]
**Describe the bug**
http_request_duration_seconds metric is missing.

**To Reproduce**
1. Go to the endpoint `/metrics`

**Actual behavior**
Cannot find :
- http_request_duration_seconds_bucket, 
- http_request_duration_seconds_sum, 
- http_request_duration_seconds_count

**Expected behavior**
- should be present 

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.2.1
 - Browser: Chrome Version 121.0.6167.160
 - Strapi version : v4.16.2

**Comment by XanderD99** [comment]
Seems to be working fine for me.

do not that the metric is called http_request_duration_s not http_request_duration_seconds.

**Comment by lrasata** [comment]
Oh... yes indeed it is now called `http_request_duration_s` not `http_request_duration_seconds` anymore. 
Closing this ticket. Thank you for your prompt answer.
