### ISSUE TITLE
Separate port for prometheus metrics without authorization

### ISSUE THREAD

**Issue by ginn13** [XanderD99/strapi-prometheus#22]
It is possible to add another listener only for metrics, to use it without auth token? It is useful in k8s environments, where separate metrics port not exposed outside cluster and therefore not visible to external clients

**Comment by XanderD99** [comment]
right now that is not possible, this would however be a great addition to the package

**Comment by XanderD99** [comment]
hey @ginn13 I just created a new version where you can enable the metrcis to run on separate listener. 

Right now it still starts and stops together with your main strapi instance but it run on separate http port. More info is in the readme. If any issues come up with this feel free to let me know
