### ISSUE TITLE
Enable collect functions for custom metric

### ISSUE THREAD

**Issue by aw030** [XanderD99/strapi-prometheus#23]
Hi!

Can you please enable support for the collect functions of metric options item in register(metric) function /services/metrics.js. Is adding collect callbacks supported at the moment? if yes a documentation will be helpful. Will it be possible to add this feature if not supported, i also could prepare a pull request if needed. Greetz!

```
register(metric) {
      . . .
      const options = {
        name: '${prefix}${metric.name}',
        help: metric.help,
        buckets: metric.buckets || [],
        labelNames: metric.labelNames || [],
        registers: [register],
        collect: metric.collect // Here
      }

      // Or here
      if (typeof metric.collect === "function") {
        options.collect = metric.collect;
      }
       . . .
    }
```

**Comment by XanderD99** [comment]
Hi!

a small patch has been released (v1.9.2) where all options are forwarded to the type constructor. So any option that the metric type can hold can be forwarded. 
Only name and registers will get overwritten by the those used by the package. (This could be a future improvement =))
