### ISSUE TITLE
How does one add the Grafana dashboard to this?

### ISSUE THREAD

**Issue by KeystoneScience** [XanderD99/strapi-prometheus#3]
Not an issue, but it would be great to have a little bit of documentation on how to integrate Grafana into this! I have been looking around and haven't been able to figure it out. Thanks!

**Comment by XanderD99** [comment]
It's indeed not completely clear in my readme but let me clarify how I use it.

Right now you cannot integrate it into the Strapi dashboard (is planned for when I find the time), you will have to set up your own Grafana dashboard. When you have done that you'll have to create a data source, I recommend using Prometheus (example config is in the readme). After that, you can add that data source in Grafana and start using it.

Some useful links:
- [grafana setup](https://grafana.com/docs/grafana/latest/setup-grafana/installation/)
- [prometheus setup](https://prometheus.io/docs/prometheus/latest/getting_started)
- [grafana and prometheus](https://grafana.com/docs/grafana/latest/getting-started/get-started-grafana-prometheus)

**Comment by KeystoneScience** [comment]
Ohhh gotcha. I was under the assumption that this was spinning up an instance of prometheus as well. Sorry for that confusion, and thanks for the fast response!
