### ISSUE TITLE
Can't access /api/metrics using api token

### ISSUE THREAD

**Issue by rodgeraraujo** [XanderD99/strapi-prometheus#4]
**Describe the bug**
I cannot access the route using an API token. Even adding the route in (Settings ->U&P->Roles->authenticated->plugin name).

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] mac os
 - Browser [e.g. chrome, safari]: chrome
 - Version [e.g. 22]: v0.6.2

**Additional context**
When I try to make a request, I always get a 403 Forbidden response.

**Comment by XanderD99** [comment]
Okay so I did some testing and found that when the token is set to Read only (which should be enough as you only need to read) indeed returns a 403. However when I create a token that has full access it works as intended. 

So for now I would say to create a new token that has full access and I will look further into why it doesn't work with only read access.

**Comment by rodgeraraujo** [comment]
Yeah, I think is a Strapi problem. Because I have same issue with a custom route, only works if full access token, even though the route is just GET. read-only should work normally. Thank you friend!

**Comment by XanderD99** [comment]
I did some digging and found a solution to the bug and how to fix your issue with the custom router as well. 

apparently you need to add a scope property for the auth to work. (It doesn't seem to be documented anywhere). I added it into the plugin and tested it with a read only token and it seemed to work just fine. So I published version 0.6.3 with the fix.

you can find more info here
https://forum.strapi.io/t/403-for-custom-route-api-token/15031
