### ISSUE TITLE
Default node version

### ISSUE THREAD

**Issue by Dispersia** [XanderD99/strapi-prometheus#8]
Hello, we are currently using node 18, but this has a requirement for < 17. Is this a hard failure that it doesn't work on higher versions, or can the required node version be removed?

**Comment by XanderD99** [comment]
No it should work with higher versions as well, I haven't tested it with node >= 17 directly but both dependencies work perfectly fine with node >= 17.

I updated the package.json to `"node": ">=14.19.1 <=18.x.x"` conform to strapi and released a new version (1.1.1) to npm!

**Comment by Dispersia** [comment]
thank you for the super fast turn around!
