### ISSUE TITLE
When strapi-prometheus plugin is disabled and strapi-prometheus.metrics middleware has been added, strapi app doesnt start

### ISSUE THREAD

**Issue by lrasata** [XanderD99/strapi-prometheus#9]
**Describe the bug**
When strapi-prometheus plugin is disabled and strapi-prometheus.metrics middleware has been added, strapi app doesnt start

**To Reproduce**
1. Install strapi-prometheus : 'yarn add strapi-prometheus'
2. Add plugin config in `config/plugins.js` as shown [here](https://market.strapi.io/plugins/strapi-prometheus)
3. Set `enabled` attribute to `false` for `strapi-prometheus`
4. Add the middleware `plugin::strapi-prometheus.metrics` in `config/middlewares.js`
5. Run `yarn develop`

**Actuall outcome in logs**
```
$ strapi develop
[2022-11-24 09:51:14.764] debug: ⛔️ Server wasn't able to start properly.
[2022-11-24 09:51:14.765] error: Invalid middleware configuration. Expected Array<string|{name?: string, resolve?: string, config: any}.
Error: Invalid middleware configuration. Expected Array<string|{name?: string, resolve?: string, config: any}.
```

**Expected behavior**
App should starts normally.
the expectation is : if an external plugin has a middleware declared in `config/middlewares.js`, if that external plugin is disabled, the middleware of the plugin should not be automatically added...

**Environment (please complete the following information):**
 - OS: MacOS Ventura 13.0
 - Browser: Chrome
 - Strapi: v4.4.5
 - strapi-prometheus: 1.1.1

**Comment by XanderD99** [comment]
Thanks for reporting this issue. This wasn't something I thought of when creating the package, I'll get this fixed asap.

**Comment by XanderD99** [comment]
@lrasata I made some changes. The middleware is now injected automatically when the plugin is loaded, so you don't need to manually add it to your `middleware.js` this also prevents your error of middleware not found from happening whenever the plugin is disabled.

Upgrade to version 1.2.0 for these changes to take effect.

**Comment by lrasata** [comment]
> @lrasata I made some changes. The middleware is now injected automatically when the plugin is loaded, so you don't need to manually add it to your `middleware.js` this also prevents your error of middleware not found from happening whenever the plugin is disabled.
> 
> Upgrade to version 1.2.0 for these changes to take effect.

Thanks very much! will have a try
